# Generated by Django 4.2.2 on 2023-08-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='monthly_cutting_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
