# Generated by Django 4.2.2 on 2023-08-27 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_alter_loan_monthly_cutting_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='percentage_of_loan_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_cutting_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
