# Generated by Django 4.2.2 on 2023-09-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_remove_loan_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loancomment',
            old_name='text',
            new_name='comment',
        ),
    ]
