# Generated by Django 4.2.4 on 2023-08-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0028_employee_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='joining_date',
            new_name='joindate',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='attachment',
            new_name='attach',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='expiry_date',
            new_name='date_expiry',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='monthly_cutting_amount',
            new_name='monthly_cutting_value',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employid',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='monthly_cutting_percentage',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_number',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='payroll',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.payroll'),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_cutting_type',
            field=models.CharField(choices=[('%', '%'), ('amount', 'Amount')], default='%', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_info', to='zohoapp.employee'),
        ),
    ]
